[package]
name = "abstracto"
version = "0.1.0"
edition = "2018"
authors = ["Alexey Golubev <dr.freecx@gmail.com>"]

[[example]]
name = "demo1"

[[example]]
name = "demo2"

[[example]]
name = "demo3"

[[example]]
name = "demo4"

[[example]]
name = "demo5"
